### ISSUE TITLE
What is the velocity unit ?

### ISSUE THREAD

**Issue by Bug38** [arduino-libraries/ArduinoMotorCarrier#11]
Hi,

I'm trying to use the PID velocity mode but I can't figure which unit it uses...
I'm working with a motor which has a 12 poles encoder, 88 ration gearbox reducer and I try to set it turn at 0.63 turn per second.
I saw that encoders count each change of the two sensors, so I figured a 3696 ticks/seconds velocity.

BUT, when I set-up the pid, I see that it turns WAY too fast and by printing `encoder1.getCountPerSecond()` I can read `63`.

Have you an answer or some tips for me ?

Thanks

Bug38

EDIT :
Just saw that :
`for now just use the difference in count since the last period as this is more than sufficient for now for use as angular velocity` 
And it seems that this method is rescheduled every 10ms. Is it precise enough or should we take into account the last timestamp? For now it seems it allows an error of 100 - 200 ticks / seconds.

**Comment by facchinm** [comment]
@ErnestoELC can you take a look?

**Comment by ErnestoELC** [comment]
Hello Bug38,
The reason for the last timestamp is because the call to populateRegisters_wrapper() is rescheduled every X ms defined when you instantiate the PID:
`PIDWrapper(encoders[0].position, encoders[0].velocity, &dcmotors[0], 0, 10, 100), //10ms period velo, 100ms period pos .`

So basically as it is right now, depending on how frequent you set this eventCall you will get a different unit for countsPerSecond. The default unit is counts/10ms.

Hope this helps!
